nav:
  - Home: index.md
  - General instructions: Labs/general_instructions.md
  - Lab0: Labs/Lab0.md

site_name: Advanced Database Labs
site_author: "Amira Nasreldeein, Aseel, Salma"
site_description: "A collection of lab assignments for the ADB 2025 course."
theme:
  favicon: image/fmsi.png
  logo: image/fmsi.png
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
      primary: blue
      accent: pink
    - scheme: slate 
      toggle:
        icon: material/brightness-4
        name: Switch to light mode    
      primary: blue
      accent: pink

plugins:
  - search
  - glightbox
  - with-pdf:
      output_path: pdf/document.pdf
      enabled_if_env: ENABLE_PDF_EXPORT
      cover_subtitle: "ADB Labs"

extra_javascript:
   - js/open_links.js

extra_css:
   - stylesheets/extra.css

markdown_extensions:
  - pymdownx.blocks.caption
  - attr_list
  - md_in_html
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

copyright:
  © 2025 Amira – Aseel – Salma
